# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'run.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(249, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton_search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_search.setObjectName("pushButton_search")
        self.horizontalLayout_2.addWidget(self.pushButton_search)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_setting_advanced = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_setting_advanced.setCheckable(True)
        self.pushButton_setting_advanced.setChecked(True)
        self.pushButton_setting_advanced.setDefault(False)
        self.pushButton_setting_advanced.setFlat(False)
        self.pushButton_setting_advanced.setObjectName("pushButton_setting_advanced")
        self.horizontalLayout_2.addWidget(self.pushButton_setting_advanced)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.frame_advanced = QtWidgets.QFrame(self.centralwidget)
        self.frame_advanced.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_advanced.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_advanced.setObjectName("frame_advanced")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_advanced)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_unlimite_time_flag = QtWidgets.QCheckBox(self.frame_advanced)
        self.checkBox_unlimite_time_flag.setChecked(True)
        self.checkBox_unlimite_time_flag.setObjectName("checkBox_unlimite_time_flag")
        self.horizontalLayout.addWidget(self.checkBox_unlimite_time_flag)
        self.label = QtWidgets.QLabel(self.frame_advanced)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.dateEdit = QtWidgets.QDateEdit(self.frame_advanced)
        self.dateEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        self.dateEdit.setMaximumSize(QtCore.QSize(400, 16777215))
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2002, 10, 10), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(QtCore.QDate(2002, 10, 10))
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout.addWidget(self.dateEdit)
        self.label_2 = QtWidgets.QLabel(self.frame_advanced)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.frame_advanced)
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.horizontalLayout.addWidget(self.dateEdit_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_sort_flag = QtWidgets.QCheckBox(self.frame_advanced)
        self.checkBox_sort_flag.setChecked(True)
        self.checkBox_sort_flag.setObjectName("checkBox_sort_flag")
        self.horizontalLayout_3.addWidget(self.checkBox_sort_flag)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(self.frame_advanced)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.comboBox_type = QtWidgets.QComboBox(self.frame_advanced)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_type.sizePolicy().hasHeightForWidth())
        self.comboBox_type.setSizePolicy(sizePolicy)
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_type)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label_4 = QtWidgets.QLabel(self.frame_advanced)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.comboBox_name = QtWidgets.QComboBox(self.frame_advanced)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_name.sizePolicy().hasHeightForWidth())
        self.comboBox_name.setSizePolicy(sizePolicy)
        self.comboBox_name.setObjectName("comboBox_name")
        self.comboBox_name.addItem("")
        self.comboBox_name.addItem("")
        self.comboBox_name.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_name)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_show_path = QtWidgets.QLabel(self.frame_advanced)
        self.label_show_path.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_show_path.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_show_path.setObjectName("label_show_path")
        self.horizontalLayout_7.addWidget(self.label_show_path)
        self.pushButton_change_save_path = QtWidgets.QPushButton(self.frame_advanced)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_change_save_path.sizePolicy().hasHeightForWidth())
        self.pushButton_change_save_path.setSizePolicy(sizePolicy)
        self.pushButton_change_save_path.setObjectName("pushButton_change_save_path")
        self.horizontalLayout_7.addWidget(self.pushButton_change_save_path)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_filter_title = QtWidgets.QLineEdit(self.frame_advanced)
        self.lineEdit_filter_title.setObjectName("lineEdit_filter_title")
        self.gridLayout.addWidget(self.lineEdit_filter_title, 0, 1, 1, 1)
        self.checkBox_filter_title = QtWidgets.QCheckBox(self.frame_advanced)
        self.checkBox_filter_title.setObjectName("checkBox_filter_title")
        self.gridLayout.addWidget(self.checkBox_filter_title, 0, 0, 1, 1)
        self.lineEdit_filter_content = QtWidgets.QLineEdit(self.frame_advanced)
        self.lineEdit_filter_content.setObjectName("lineEdit_filter_content")
        self.gridLayout.addWidget(self.lineEdit_filter_content, 1, 1, 1, 1)
        self.checkBox_filter_content = QtWidgets.QCheckBox(self.frame_advanced)
        self.checkBox_filter_content.setObjectName("checkBox_filter_content")
        self.gridLayout.addWidget(self.checkBox_filter_content, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_4.addWidget(self.frame_advanced)
        self.tabWidget_title = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_title.setObjectName("tabWidget_title")
        self.tab_title = QtWidgets.QWidget()
        self.tab_title.setObjectName("tab_title")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_title)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget_title = QtWidgets.QTableWidget(self.tab_title)
        self.tableWidget_title.setObjectName("tableWidget_title")
        self.tableWidget_title.setColumnCount(0)
        self.tableWidget_title.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget_title)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_title_up = QtWidgets.QPushButton(self.tab_title)
        self.pushButton_title_up.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_title_up.setObjectName("pushButton_title_up")
        self.horizontalLayout_4.addWidget(self.pushButton_title_up)
        self.label_page_info_title = QtWidgets.QLabel(self.tab_title)
        self.label_page_info_title.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_page_info_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_page_info_title.setObjectName("label_page_info_title")
        self.horizontalLayout_4.addWidget(self.label_page_info_title)
        self.pushButton_title_down = QtWidgets.QPushButton(self.tab_title)
        self.pushButton_title_down.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_title_down.setObjectName("pushButton_title_down")
        self.horizontalLayout_4.addWidget(self.pushButton_title_down)
        self.lineEdit_title_page = QtWidgets.QLineEdit(self.tab_title)
        self.lineEdit_title_page.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_title_page.setObjectName("lineEdit_title_page")
        self.horizontalLayout_4.addWidget(self.lineEdit_title_page)
        self.pushButton_title_jump_to = QtWidgets.QPushButton(self.tab_title)
        self.pushButton_title_jump_to.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_title_jump_to.setObjectName("pushButton_title_jump_to")
        self.horizontalLayout_4.addWidget(self.pushButton_title_jump_to)
        self.checkBox_select_title = QtWidgets.QCheckBox(self.tab_title)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_select_title.sizePolicy().hasHeightForWidth())
        self.checkBox_select_title.setSizePolicy(sizePolicy)
        self.checkBox_select_title.setObjectName("checkBox_select_title")
        self.horizontalLayout_4.addWidget(self.checkBox_select_title)
        self.pushButton_download_select_title = QtWidgets.QPushButton(self.tab_title)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_download_select_title.sizePolicy().hasHeightForWidth())
        self.pushButton_download_select_title.setSizePolicy(sizePolicy)
        self.pushButton_download_select_title.setObjectName("pushButton_download_select_title")
        self.horizontalLayout_4.addWidget(self.pushButton_download_select_title)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.tabWidget_title.addTab(self.tab_title, "")
        self.tab_content = QtWidgets.QWidget()
        self.tab_content.setObjectName("tab_content")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_content)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_content = QtWidgets.QTableWidget(self.tab_content)
        self.tableWidget_content.setObjectName("tableWidget_content")
        self.tableWidget_content.setColumnCount(0)
        self.tableWidget_content.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget_content)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_content_up = QtWidgets.QPushButton(self.tab_content)
        self.pushButton_content_up.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_content_up.setObjectName("pushButton_content_up")
        self.horizontalLayout_5.addWidget(self.pushButton_content_up)
        self.label_page_info_content = QtWidgets.QLabel(self.tab_content)
        self.label_page_info_content.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_page_info_content.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_page_info_content.setAlignment(QtCore.Qt.AlignCenter)
        self.label_page_info_content.setObjectName("label_page_info_content")
        self.horizontalLayout_5.addWidget(self.label_page_info_content)
        self.pushButton_content_down = QtWidgets.QPushButton(self.tab_content)
        self.pushButton_content_down.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_content_down.setObjectName("pushButton_content_down")
        self.horizontalLayout_5.addWidget(self.pushButton_content_down)
        self.lineEdit_content_page = QtWidgets.QLineEdit(self.tab_content)
        self.lineEdit_content_page.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_content_page.setObjectName("lineEdit_content_page")
        self.horizontalLayout_5.addWidget(self.lineEdit_content_page)
        self.pushButton_content_jump_to = QtWidgets.QPushButton(self.tab_content)
        self.pushButton_content_jump_to.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_content_jump_to.setObjectName("pushButton_content_jump_to")
        self.horizontalLayout_5.addWidget(self.pushButton_content_jump_to)
        self.checkBox_select_content = QtWidgets.QCheckBox(self.tab_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_select_content.sizePolicy().hasHeightForWidth())
        self.checkBox_select_content.setSizePolicy(sizePolicy)
        self.checkBox_select_content.setObjectName("checkBox_select_content")
        self.horizontalLayout_5.addWidget(self.checkBox_select_content)
        self.pushButton_download_select_content = QtWidgets.QPushButton(self.tab_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_download_select_content.sizePolicy().hasHeightForWidth())
        self.pushButton_download_select_content.setSizePolicy(sizePolicy)
        self.pushButton_download_select_content.setObjectName("pushButton_download_select_content")
        self.horizontalLayout_5.addWidget(self.pushButton_download_select_content)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.tabWidget_title.addTab(self.tab_content, "")
        self.verticalLayout_4.addWidget(self.tabWidget_title)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_title.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "券商报告获取系统"))
        self.pushButton_search.setText(_translate("MainWindow", "搜索"))
        self.pushButton_setting_advanced.setText(_translate("MainWindow", "高级"))
        self.checkBox_unlimite_time_flag.setText(_translate("MainWindow", "不限时间"))
        self.label.setText(_translate("MainWindow", "开始时间"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "yyyy/M/d"))
        self.label_2.setText(_translate("MainWindow", "结束时间"))
        self.dateEdit_2.setDisplayFormat(_translate("MainWindow", "yyyy/M/d"))
        self.checkBox_sort_flag.setText(_translate("MainWindow", "不限排序"))
        self.label_3.setText(_translate("MainWindow", "排序类型："))
        self.comboBox_type.setItemText(0, _translate("MainWindow", "降序"))
        self.comboBox_type.setItemText(1, _translate("MainWindow", "升序"))
        self.label_4.setText(_translate("MainWindow", "排序名称："))
        self.comboBox_name.setItemText(0, _translate("MainWindow", "相关度"))
        self.comboBox_name.setItemText(1, _translate("MainWindow", "时间"))
        self.comboBox_name.setItemText(2, _translate("MainWindow", "代码"))
        self.label_show_path.setText(_translate("MainWindow", "用来显示路径"))
        self.pushButton_change_save_path.setText(_translate("MainWindow", "修改路径"))
        self.lineEdit_filter_title.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">用来过滤标题搜索和内容搜索</span>，只针对返回的标题进行过滤，语法示例：</p><p><span style=\" color:#ff0000;\">中国&amp;中车&amp;(年度|季度)</span></p><p>表示仅显示标题中含有中国，中车，年度or季度关键<span style=\" font-weight:600;\">(年度、季度二选一)</span>词的结果。</p><p>该过滤规则同样适用于下载。</p><p><br/></p></body></html>"))
        self.lineEdit_filter_title.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.checkBox_filter_title.setText(_translate("MainWindow", "过滤标题"))
        self.lineEdit_filter_content.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">只用来过滤内容搜索</span>，只针对返回的文章内容进行过滤<span style=\" font-weight:600;\">（若没有文章内容返回，则不进行过滤）</span>，语法示例：</p><p><span style=\" color:#ff0000;\">中国&amp;中车&amp;(年度|季度)</span></p><p>表示仅显示标题中含有中国，中车，年度or季度<span style=\" font-weight:600;\">(年度、季度二选一)</span>关键词的结果。</p><p>该过滤规则同样适用于下载。</p><p><br/></p></body></html>"))
        self.checkBox_filter_content.setText(_translate("MainWindow", "过滤文章"))
        self.pushButton_title_up.setText(_translate("MainWindow", "上一页"))
        self.label_page_info_title.setText(_translate("MainWindow", "0/0"))
        self.pushButton_title_down.setText(_translate("MainWindow", "下一页"))
        self.pushButton_title_jump_to.setText(_translate("MainWindow", "页面跳转"))
        self.checkBox_select_title.setText(_translate("MainWindow", "选择当页"))
        self.pushButton_download_select_title.setText(_translate("MainWindow", "下载所选"))
        self.tabWidget_title.setTabText(self.tabWidget_title.indexOf(self.tab_title), _translate("MainWindow", "标题搜索"))
        self.pushButton_content_up.setText(_translate("MainWindow", "上一页"))
        self.label_page_info_content.setText(_translate("MainWindow", "0/0"))
        self.pushButton_content_down.setText(_translate("MainWindow", "下一页"))
        self.pushButton_content_jump_to.setText(_translate("MainWindow", "页面跳转"))
        self.checkBox_select_content.setText(_translate("MainWindow", "选择当页"))
        self.pushButton_download_select_content.setText(_translate("MainWindow", "下载所选"))
        self.tabWidget_title.setTabText(self.tabWidget_title.indexOf(self.tab_content), _translate("MainWindow", "内容搜索"))

